### ISSUE TITLE
[HTTPError: 401 Client Error: Unauthorized for url]

### ISSUE THREAD

**Issue by PhoenixSmaug** [HugoLime/notion-backup#2]
It has worked perfectly for months, then suddenly it starts throwing out an HTTP error every time before there is even a chance to log in. I suspect that the API of Notion has been reworked.

```
Backup Notion workspace into directory C:\Users\phoen\Documents
Login to notion if necessary
Traceback (most recent call last):
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\phoen\Documents\venv\Scripts\backup_notion.exe\__main__.py", line 9, in <module>
  File "c:\users\phoen\documents\venv\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\phoen\documents\venv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\phoen\documents\venv\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\phoen\documents\venv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\phoen\documents\venv\lib\site-packages\notion_backup\backup_service.py", line 106, in main
    backup_service.backup()
  File "c:\users\phoen\documents\venv\lib\site-packages\notion_backup\backup_service.py", line 58, in backup
    user_content = self.notion_client.get_user_content()
  File "c:\users\phoen\documents\venv\lib\site-packages\notion_backup\notion_client.py", line 51, in get_user_content
    return self._send_post_request("loadUserContent", {})["recordMap"]
  File "c:\users\phoen\documents\venv\lib\site-packages\notion_backup\notion_client.py", line 47, in _send_post_request
    response.raise_for_status()
  File "c:\users\phoen\documents\venv\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://www.notion.so/api/v3/loadUserContent
```

**Comment by HugoLime** [comment]
Stored credentials are invalidated after some time.
From version 0.2.2, a new authentication is done if the credentials are invalid.
